## Numpy

messing with numpy

In [1]:
import numpy as np

a =np.array([1,2,3])
print (a)

[1 2 3]


In [2]:
b = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(type(b), b.shape, b[0],b[1], b[2])
b[1] = 3   #in the row 1 numbers will be replaced by 3
print (b)

<class 'numpy.ndarray'> (3, 4) [1 2 3 4] [5 6 7 8] [ 9 10 11 12]
[[ 1  2  3  4]
 [ 3  3  3  3]
 [ 9 10 11 12]]


In [3]:
a =np.ones(3) #this will generate 3 numbers, all number 1
print (a)

[1. 1. 1.]


In [4]:
a =np.zeros(3) #this will generated 3 numbers, each zero
print (a)

[0. 0. 0.]


In [5]:
a = np.random.random(3) #this will generate 3 random numbers
print (a)

[0.63129139 0.82555471 0.08662102]


In [7]:
a = np.ones((4,3,2)) #this will generate 4 arrays, in each will be 3 rows and 2 columns,all numbers are number 1
print (a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [9]:
a = np.random.random((5,3,2)) #this will generate 5 arrays, in each will be 3 rows and 2 columns,all numbers are random numbers
print (a)

[[[0.48801233 0.14271733]
  [0.30240554 0.05213376]
  [0.9688718  0.73619379]]

 [[0.75987525 0.0681316 ]
  [0.194585   0.23150276]
  [0.70293944 0.72075983]]

 [[0.09546028 0.27614317]
  [0.17299557 0.48592443]
  [0.11243776 0.17354154]]

 [[0.47848625 0.88223409]
  [0.30441308 0.87877485]
  [0.34181442 0.33186936]]

 [[0.33538259 0.3272209 ]
  [0.36323764 0.67124201]
  [0.1043719  0.25520438]]]


In [12]:
a = np.full((4,3), 5) #this will created array with 4 rows, 3 columns filled with number 5
print (a)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [15]:
a = np.eye (3) #this will create 3x3 identity matrix
print (a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
a = np.arange(10,50,5) #this will create array of values starting at 10 and increments of 5
print (a)              #this will ends on 45, not 50 - doesn't include the top end of the interval

[10 15 20 25 30 35 40 45]


In [44]:
a = np.linspace (0.,1., num=5) #this will print 5 numbers from interval of the numbers zero to 1
print (a)

[0.   0.25 0.5  0.75 1.  ]


### Stacking arrays

If we need to stack the existing arrays, either vertically or horizontaly we use `vstack()` (or `row_stack`) and `hstack()` (or `column_stack`)

In [25]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b)) #this will stack two arrays vertically

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a = np.array([[7],[8],[9]])
b = np.array([[10],[11],[12]])
np.hstack((a,b))  #this will stack two arrays horizontally

array([[ 7, 10],
       [ 8, 11],
       [ 9, 12]])

### Idexing

In [36]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print (a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [28]:
print (a[0]) #this will print first number in first column (we account from zero not one)

1


In [37]:
print(a[1,3]) #this will print out 3rd number (3rd column) in second row

9


In [47]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(b[1:3]) #this will print row 1 up to 3 each column

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [48]:
print(b[1:3,2]) #this will print out from row 1 to 3, number in 3rd (8 & 13) column of each row

[ 8 13]


In [49]:
# Create the following rank 2 array with shape (3, 5)
# [[ 1  2  3  4 5]
#  [ 6  7  8  9 10]
#  [ 11 12 13 14 15]]

b = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
c = b[:2, 1:3] #this will look on rows up to 2 - first 2 rows, and print out number in 1st and 2nd column
print (c)

[[2 3]
 [7 8]]


In [52]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
row_r1 = a[0, :]    # Rank 1 view of the first row of, ':' means that it will take all columns
row_r2 = a[1:2, :]  # Rank 2 view of the second row of, ':' means that it will take all columns
row_r3 = a[[2], :]  # Rank 3 view of the third row of, ':' means that it will take all columns
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[1 2 3 4 5] (5,)
[[ 6  7  8  9 10]] (1, 5)
[[11 12 13 14 15]] (1, 5)


In [54]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print()
print(col_r2, col_r2.shape)

[ 2  7 12] (3,)

[[ 2]
 [ 7]
 [12]] (3, 1)


In [56]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])


[1 4 5]


In [57]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


In [58]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


In [59]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [60]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"


[ 1  6  7 11]


In [61]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### End