In [36]:
from typing import NamedTuple
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

n_repeats = 5
class Attack(NamedTuple):
    n_attackers: int
    n_defenders: int
options = [Attack(3,2)]

rng = np.random.default_rng()
for option in options:
    print(option)
    attacker = rng.integers(
        1, 7, size=(n_repeats, option.n_attackers)
    )
    print("original list\n",attacker)
    attacker_sorted = np.sort(attacker, axis = 1)[:, ::-1]
    print("Sorted list\n", attacker_sorted)
    
    defender = rng.integers(
        1, 7, size=(n_repeats, option.n_defenders)
    )
    print("original list\n",defender)
    defender_sorted = np.sort(defender, axis = 1)[:, ::-1]
    print("Sorted list\n", defender_sorted)
    print()

attacker_list = []
defender_list = []

def round ():
 
    attacker_loss = 0
    defender_loss = 0

    if attacker_sorted [0] > defender_sorted [0]:
        defender_loss += 1
    else:
        attacker_loss +=1
    return attacker_loss, defender_loss

attacker_loss, defender_loss = round()

#attacker_list.append(attacker_loss)
#[defender_list.append(defender_loss)

print(f"attacker losses: {attacker_loss},defender lossess: {defender_loss}")


Attack(n_attackers=3, n_defenders=2)
original list
 [[6 4 4]
 [1 1 4]
 [4 3 2]
 [1 1 4]
 [2 1 5]]
Sorted list
 [[6 4 4]
 [4 1 1]
 [4 3 2]
 [4 1 1]
 [5 2 1]]
original list
 [[5 2]
 [1 4]
 [3 2]
 [2 6]
 [1 3]]
Sorted list
 [[5 2]
 [4 1]
 [3 2]
 [6 2]
 [3 1]]



ValueError: operands could not be broadcast together with shapes (3,) (2,) 